### ISSUE TITLE
Unable to run query

### ISSUE THREAD

**Issue by ghuron** [mw2sparql/mw2sparql#5]
Trying to run https://tools.wmflabs.org/mw2sparql/sparql?query=select+*+%7B%3Chttps%3A%2F%2Fen.wikipedia.org%2Fwiki%2FSPARQL%3E+%3Fpredicate+%3Fobject%7D
get
org.eclipse.rdf4j.repository.RepositoryException: it.unibz.inf.ontop.exception.OntopConnectionException: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [jdk-http-server-13] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:20; busy:20; idle:0; lastwait:30000].

**Comment by Tpt** [comment]
It's probably because all connections to the database are already used to execute some query. Improving performances should help here.

**Comment by ghuron** [comment]
I was able to reproduce it locally. By default, ontop creates DB connection pool with maximum 20 active connections. Unfortunately during each evaluate() 1 connection is leaked (see #6 for details) so your 21 query will fail with PoolExhaustedException

**Comment by ghuron** [comment]
#6 seems to fix #5
